#FROM maven:3.2.3-jdk-8 AS build

#ARG version

#RUN git clone https://github.com/WeBankFinTech/DataSphereStudio/releases/tag/${version} DataSphereStudio

#RUN cd DataSphereStudio && mvn -N  install && mvn clean install


FROM openjdk:8u232-jdk

ADD wedatasphere-dss-0.5.0-dist.tar /dss




